dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=find_my_frog
    - TARGET=x86_64-unknown-linux-gnu

rust:
  - stable

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

deploy:
  provider: releases
  api_key:
    secure: VFyzY1QnqI1KL6gR+meBurHW42yfly1CF5werWtNtH7RhbAZiG/RbDMhDgMwL7KbvHuwONL6KFDrydN0fhkZWJ42Eqavec2pG+WnRE7KQmiMy85MYNTq73XEYUGhmvqB6e4kbDEsih27YeEdIsjyEjXB/ZPHGWQr4PbB+4PMUAPpWlbRmbt0iVX7ghbZ7vHX+S5LDgkgVjRJ1oioZsq8gX849/NxNPXWssXqhihMPNA43tB8Z9vqTPXuNVlsYDtxoUn3B3qwOWzTDWe/8rejJ71C7cgMOPknscqrgX1A9Wnx2NAFrJQ3XT95FdSLAzXCxZBhl++dI4VxPsH3/7CryWQBgM3mwQ2+rjSVzlp2IV1WKdSGsbUg9BOo0fvQggchn+i9x4wlDEdGYg7rCVFx/+/5+mTLy+xiABVjfYa8n9aD2nOg/EMc/mxAkF7F+8nWRlPUqJHScm6/a/oER65PitnjF4Z4nv2m8++Z3sYSsHw6tU4u89gDe8ISvTmynCxQ06sp8aOVfOOco8R1aJDa0hNRwb4EuE05CFZ4xxqmkkGDKv333dPn/fwhbgpGLOpdc/mCP5XJot+m2YFQMjNUGM9S8XUGaoD8N0LuRUAUn5HbDVG5fX2WnDn7fbetMcoEwzhEG2QPOSekB21UXZK1coX+fABq/3uixZXDpAFmO+o=
  file_glob: true
  file: ${CRATE_NAME}-${TRAVIS_TAG}-${TARGET}.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true

notifications:
  email:
    on_success: never

# burp
